name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Setup Docker
        run: './scripts/buildprod.sh'


